# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Standard_quan',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('quantities', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
