# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cook', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Ingre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantities', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('steps', models.CharField(max_length=2000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rec_ingre',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='rec_ingre',
            unique_together=set([('rid', 'iid')]),
        ),
    ]
