# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 08:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cook', '0005_auto_20161207_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rid_next', to='cook.Recipe')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rid_prev', to='cook.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('revid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('suggestion', models.CharField(max_length=500)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('time', models.DateTimeField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Recipe')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='rec_tag',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('rid', 'relatedrid')]),
        ),
        migrations.AlterUniqueTogether(
            name='rec_tag',
            unique_together=set([('rid', 'tid')]),
        ),
    ]
