# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cook', '0006_auto_20161207_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Groups')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('repid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=3000)),
                ('time', models.DateTimeField()),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Member')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Rsvp'),
        ),
        migrations.AddField(
            model_name='event',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Groups'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set([('eid', 'username')]),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('gid', 'username')]),
        ),
    ]
