# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0008_auto_20161211_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Member'),
        ),
    ]
