# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0010_auto_20161214_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=b'recipe/')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Rep_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=b'report/')),
                ('repid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Report')),
            ],
        ),
        migrations.CreateModel(
            name='Rev_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to=b'review/')),
                ('revid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cook.Review')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rev_image',
            unique_together=set([('revid', 'img')]),
        ),
        migrations.AlterUniqueTogether(
            name='rep_image',
            unique_together=set([('repid', 'img')]),
        ),
        migrations.AlterUniqueTogether(
            name='rec_image',
            unique_together=set([('rid', 'img')]),
        ),
    ]
