# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 01:14
from __future__ import unicode_literals

import cook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0012_auto_20161215_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_image',
            name='img',
            field=models.FileField(upload_to=cook.models.upload_report),
        ),
        migrations.AlterField(
            model_name='rev_image',
            name='img',
            field=models.FileField(upload_to=cook.models.upload_review),
        ),
    ]
